#!/bin/bash

# Author: Santosh Pandit
# Purpose: Check if it is Debian Testing
# Last update: 26 July 2023
  
# Get the version codename from /etc/os-release
version_codename=$(grep -oP '(?<=^VERSION_CODENAME=).+' /etc/os-release | tr -d '"')

# Check if the version codename contains "testing" or "trixie"
if [[ "$version_codename" == *"testing"* ]] || [[ "$version_codename" == *"trixie"* ]]; then
    echo "Debian Testing is installed."
else
    echo "Debian Testing is not installed."
fi
