#!/bin/bash
clear
echo "*******************************************************************"
echo "* Always use every script thoroughly in a test environment first. *"
echo "*******************************************************************"
echo "* Source: https://github.com/beatquantum/leading-edge.git         *"
echo "* Author: Santosh Pandit                                          *"
echo "*******************************************************************"
rm /etc/ssh/ssh_host_*
ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N "" 
awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.reduced
mv /etc/ssh/moduli.reduced /etc/ssh/moduli
cp sshd_config.example /etc/ssh/sshd_config
service ssh restart
echo "* Please note port has been changed to 49022. You can change it again in /etc/ssh/sshd_config *"
